version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    network_mode: bridge
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: no-word-memory
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: